### ISSUE TITLE
Operation Results Show Table Matches but Search Results says No Results

### ISSUE THREAD

**Issue by joshgk00** [horacioj/dnnsearchandreplace#1]
I've installed the latest version of the module on Evoq 9.1.1. When I search for text, the module indicates that results are found in the Operation Results. When I try to see what the results are for a specific table, The Search Results section says there are no results. I've captured a video to show what is happening
https://www.screencast.com/t/Z3Hut6S8Fb

**Comment by horacioj** [comment]
Perhaps it is about the encoding. Does it happen the same for an un-encoded search for "Braid-Tinned-Copper"?

**Comment by joshgk00** [comment]
It seems to finds the text when I search by its self. When I try the un-encoded search with the same url, it doesn't find any results. 
https://www.screencast.com/t/53jQVUMR

**Comment by horacioj** [comment]
the Url should be saved encoded (or partially encoded) in the database

**Comment by joshgk00** [comment]
In the operational results if it knows there are 10 records, shouldn't the results be able to show the details of those 10 records? Even if the urls is partially encoded?
https://www.screencast.com/t/xfR97qWTEKol

**Comment by horacioj** [comment]
Cannot reproduce.
